# Generated by Django 2.2.2 on 2019-06-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0002_auto_20190617_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.BigIntegerField(unique=True, verbose_name='母牛号')),
                ('ptime', models.DateField(verbose_name='分娩时间')),
                ('water_time', models.TimeField(verbose_name='开始流水时间')),
                ('head_time', models.TimeField(verbose_name='胎儿露出时间')),
                ('organ', models.CharField(max_length=64, verbose_name='露出器官')),
                ('out_time', models.TimeField(verbose_name='胎儿娩出时间')),
                ('wtime', models.TimeField(verbose_name='胎儿排出时间')),
                ('di', models.IntegerField(verbose_name='产犊难易度')),
                ('tai', models.BooleanField(verbose_name='胎衣是否完整')),
                ('sex', models.BooleanField(verbose_name='犊牛性别')),
                ('weight', models.IntegerField(verbose_name='犊牛体重')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.BigIntegerField(unique=True, verbose_name='表单号')),
                ('ttype', models.IntegerField(verbose_name='记录类型')),
                ('time', models.TimeField(verbose_name='提交时间')),
                ('uname', models.CharField(max_length=64, verbose_name='提交用户')),
            ],
        ),
    ]
