# Generated by Django 2.2.2 on 2019-06-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0003_cow_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AddField(
            model_name='cow',
            name='rid',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='表单号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='rid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='表单号'),
        ),
    ]
